### ISSUE TITLE
Typo in `sevice` Topic

### ISSUE THREAD

**Issue by jrusso1020** [ex-aws/ex_aws_firehose#1]
* Do not use the issues tracker for help or support (try Elixir Forum, Slack, IRC, etc.)
* Questions about how to contribute are fine.

### Environment

* Elixir & Erlang versions (elixir --version):
* ExAws version `mix deps |grep ex_aws`
* HTTP client version. IE for hackney do `mix deps | grep hackney`

### Current behavior
There seems to be a typo in the tag, it is `sevice` instead of `service` so the following link https://github.com/ex-aws?q=service&type=&language= doesn't include this package

### Expected behavior
Would expect https://github.com/ex-aws?q=service&type=&language= to include this package and for the Topic to be `service`

**Comment by benwilson512** [comment]
Fixed, thanks!
